## 第8章 错误处理和资源管理
### 8-1 defer调用
- 确保函数结束时发生
- defer 是一个栈, 先进后出, 执行到defer代码时就会入栈 
- return/panic 都有可以执行
- 使用场景: Open/Close Lock/Unlock PrintHeader/PrintFooter  

```
func tryDefer() {
	for i := 0; i < 100; i++ {
		defer fmt.Println(i) //先进后出
		if i == 30 {
			// Uncomment panic to see
			// how it works with defer
			// panic("printed too many")
		}
	}
}
```

> 有个问题, panic后的defer不会执行, 那就资源的申请和释放紧挨着!!  

### 8-2 错误处理概念

```
// The error built-in interface type is the conventional interface for
// representing an error condition, with the nil value representing no error.
type error interface {
	Error() string
}

func writeFile(filename string) {
	file, err := os.OpenFile(filename,
		os.O_EXCL|os.O_CREATE|os.O_WRONLY, 0666)

	if err != nil {
		if pathError, ok := err.(*os.PathError); !ok {
			panic(err)
		} else {
			fmt.Printf("%s, %s, %s\n",
				pathError.Op,
				pathError.Path,
				pathError.Err)
		}
		return
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	f := fib.Fibonacci()
	for i := 0; i < 20; i++ {
		fmt.Fprintln(writer, f())
	}
}
```




### 8-3 服务器统一出错处理
- 使用一个包装类: 接收要处理的函数, 返回需要的函数  


### 8-4 panic和recover
- panic 抓狂, 不知什么处理  
- 停止当前函数执行
- 一直向上返回, 执行每一层的defer
- 如果没有遇见recover, 程序退出

**recover**
- 仅在defer调用中使用
- 获取panic的值 
- 如果无法处理, 可重新panic

```
func tryRecover() {
	defer func() {    //匿名函数
		r := recover()
		if r == nil {
			fmt.Println("Nothing to recover. " +
				"Please try uncomment errors " +
				"below.")
			return
		}
		if err, ok := r.(error); ok { //获取错误类型
			fmt.Println("Error occurred:", err)
		} else {
			panic(fmt.Sprintf(
				"I don't know what to do: %v", r))
		}
	}() // 函数调用

	// Uncomment each block to see different panic
	// scenarios.
	// Normal error
	//panic(errors.New("this is an error"))

	// Division by zero
	//b := 0
	//a := 5 / b
	//fmt.Println(a)

	// Causes re-panic
	//panic(123)
}
```

### 8-5 服务器统一出错处理2

- 在包装函数中声明defer匿名函数, 然后使用recover统一处理
- Go http框架里也包含recover处理, 如果应用出错不会导致程序退出!  
- 意料之中的: 使用error. 意料之外的使用panic.
```
type appHandler func(writer http.ResponseWriter,
	request *http.Request) error

func errWrapper(
	handler appHandler) func(
	http.ResponseWriter, *http.Request) {
	return func(writer http.ResponseWriter,
		request *http.Request) {
		// panic
		defer func() {
			if r := recover(); r != nil {
				log.Printf("Panic: %v", r)
				http.Error(writer,
					http.StatusText(http.StatusInternalServerError),
					http.StatusInternalServerError)
			}
		}()

		err := handler(writer, request)

		if err != nil {
			log.Printf("Error occurred "+
				"handling request: %s",
				err.Error())

			// user error
			if userErr, ok := err.(userError); ok {
				http.Error(writer,
					userErr.Message(),
					http.StatusBadRequest)
				return
			}

			// system error
			code := http.StatusOK
			switch {
			case os.IsNotExist(err):
				code = http.StatusNotFound
			case os.IsPermission(err):
				code = http.StatusForbidden
			default:
				code = http.StatusInternalServerError
			}
			http.Error(writer,
				http.StatusText(code), code)
		}
	}
}
```